# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Merge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'IQKeyboardManagerSwift'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'GoogleSignIn'
pod 'TwitterKit'
pod 'SlideMenuControllerSwift'
pod 'Google-Mobile-Ads-SDK'
  # Pods for Merge

end
